config/routes.rb
Graphene2::Application.routes.draw do
  resources :graphs

  match '/scatter' => 'graphs#scatter'

  match '/graphs/:name' => "graphs#show"

  root :to => 'graphs#index'

end

app/models/graph.rb
class Graph < ActiveRecord::Base
  attr_accessible :category, :excel_url, :graph_type, :permalink, :visualization_name

  #GRAPH_TYPES = ["scatter", "airports", "other", "other"]

  GRAPH_URLS = ["https://raw.github.com/gist/3887118/thumbnail.png",
                "https://raw.github.com/gist/3885705/thumbnail.png"]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  # GET /graphs
  # GET /graphs.json
  def index
    @graphs = Graph.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @graphs }
    end
  end

  def scatter

  end

  # GET /graphs/1
  # GET /graphs/1.json
  def show
    @graph = Graph.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @graph }
    end
  end

  # GET /graphs/new
  # GET /graphs/new.json
  def new
    @graph = Graph.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @graph }
    end
  end

  # GET /graphs/1/edit
  def edit
    @graph = Graph.find(params[:id])
  end

  # POST /graphs
  # POST /graphs.json
  def create
    @graph = Graph.new(params[:graph])

    respond_to do |format|
      if @graph.save
        format.html { redirect_to @graph, notice: 'Graph was successfully created.' }
        format.json { render json: @graph, status: :created, location: @graph }
      else
        format.html { render action: "new" }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /graphs/1
  # PUT /graphs/1.json
  def update
    @graph = Graph.find(params[:id])

    respond_to do |format|
      if @graph.update_attributes(params[:graph])
        format.html { redirect_to @graph, notice: 'Graph was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphs/1
  # DELETE /graphs/1.json
  def destroy
    @graph = Graph.find(params[:id])
    @graph.destroy

    respond_to do |format|
      format.html { redirect_to graphs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_form.html.erb
<%= form_for(@graph) do |f| %>
  <% if @graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
      <% @graph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :excel_url %><br />
    <%= f.text_field :excel_url %>
  </div>
  <div class="field">
    <%= f.label :graph_type %><br />
    <%= f.text_field :graph_type %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :visualization_name %><br />
    <%= f.text_field :visualization_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graphs/edit.html.erb
<h1>Editing graph</h1>

<%= render 'form' %>

<%= link_to 'Show', @graph %> |
<%= link_to 'Back', graphs_path %>

app/views/graphs/index.html.erb
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<link rel="canonical" href="http://d3js.org/">
<title>Graphene | Beautiful Data</title>
<head>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %> 
  <script src="http://code.jquery.com/jquery-latest.min.js"
        type="text/javascript"></script>
  <script src="assets/d3.js"></script>
  <script src="assets/d3.min.js"></script>
  <script src="assets/geo.js"></script>
  <script src="assets/geom.js"></script>
  <script src="assets/dsv.js"></script>
  <script src="assets/csv.js"></script>
  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  <script type="text/javascript"> 
    filepicker.setKey('AYdPBJoBRaKh7NvZBMy0Qz');
    var name = $('#name').val();
    if (name != '') {
    filepicker.pickAndStore({},{},function(fpfiles){
      var file = {};
      file['url'] = fpfiles['url'];
 
    });
       window.location("/" + name);
    }
  </script>
</head>
<body>
  <div id="body">
    <%= form_for(Graph.new(), :id => "graph") do |f| %>
      <ul id="graph_form">
      <li class="field" id="graph_type">
        <%= f.select(:graph_type, Graph::GRAPH_URLS) %>  
            <div class="picker">
                <% Graph::GRAPH_URLS.each do |url| %>
                    <span class="option"><%= image_tag(url) %></span>
                <% end %>
            </div>
      </li>
      <li class="field">
        <%= f.label :permalink %><br />
        <%= f.text_field :permalink %>
      </li>
       <li class="field">
        <%= f.label :excel_url %><br />
        <%= f.text_field :excel_url %>
      </li>
       <li class="field">
          <%= f.label :category %><br />
        <%= f.text_field :category %>
      </li>
       <li class="field">
        <%= f.label :visualization_name %><br />
        <%= f.text_field :visualization_name %>
      </li>
    </ul>
    <% end %>

<form> 
   Graph Name<input id="name" type="text" name="name"/><br />
   File<input type="filepicker" name="file"/><br />
   <input type="submit" />
</form>

</body>
</html>

app/views/graphs/map.html.erb
<%= javascript_include_tag :defaults %>

app/views/graphs/new.html.erb
<h1>New graph</h1>

<%= render 'form' %>

<%= link_to 'Back', graphs_path %>

app/views/graphs/scatter.html.erb
	
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= csrf_meta_tags %> 
	<script src="http://code.jquery.com/jquery-latest.min.js"
        type="text/javascript"></script>
	<script src="assets/d3.js"></script>
	<script src="assets/d3.min.js"></script>
	<script src="assets/geo.js"></script>
	<script src="assets/geom.js"></script>
	<script src="assets/dsv.js"></script>
	<script src="assets/csv.js"></script>
	<script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
	<script type="text/javascript">

	filepicker.setKey('AYdPBJoBRaKh7NvZBMy0Qz')

	//var file_link = "https://www.filepicker.io/api/file/yvYfZwOkTlW0JswdLrrn"
	//var fpfile = {url: file_link,filename: 'scatter.csv', mimetype: 'text/plain', isWriteable: true, size: 200};
	var data = [[0,2,3],[1,4,1],[2,4,2],[3,6,4],[4,2,8],[4,9,1]];/*
filepicker.read(fpfile, function(d){
		console.log(d);
		data = d; 
      });
	*/
		filepicker.pickAndStore({extension:'.csv'}, {location:'S3'}, function(FPFiles){
			console.log(FPFiles[0]['url']);
			d3.csv(FPFiles['url'], function(points) {


				points.forEach(function(point){
					console.log(point.x);
					var p = [];
					p.push(point.x);
					p.push(point.y);
					data.push(p);
				});
				
				data.forEach(function(point){
					point.forEach(function(coor){
						console.log(coor);
					})
				})

				var w = 500;
				var h = 250;
				var svg = d3.select("body")
				.append("svg")
				.attr("width",w)
				.attr("height",h);
				var xScale = d3.scale.linear()
				.domain([0,d3.max(data,function(d){ return d[0];})])
				.range([0,w-20]);
				var yScale = d3.scale.linear()
				.domain([0,d3.max(data,function(d){ return d[1];})])
				.range([0,h-20]);
				svg.selectAll("circle")
				.data(data)
				.enter()
				.append("circle")
				.attr("cx",function(d) { return xScale(d[0]); })
				.attr("cy",function(d) { return yScale(d[1]); })
				.attr("r",5);
				svg.selectAll("text")
				.data(data)
				.enter()
				.append("text")
				.text(function(d){ return d[0] + "," + d[1]; })
				.attr("x",function(d){ return  xScale(d[0])+8;  })
				.attr("y",function(d){ return yScale(d[1])+3; })
				.attr("font-family","sans-serif")
				.attr("font-size","11px");

				var scale = d3.scale.linear();
				scale.domain([0,200]);
				scale.range([0,100]);
			});
});


	
	
	</script>
		<input type="filepicker" name="myName"/ id="pick">

app/views/graphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Permalink:</b>
  <%= @graph.permalink %>
</p>

<p>
  <b>Excel url:</b>
  <%= @graph.excel_url %>
</p>

<p>
  <b>Graph type:</b>
  <%= @graph.graph_type %>
</p>

<p>
  <b>Category:</b>
  <%= @graph.category %>
</p>

<p>
  <b>Visualization name:</b>
  <%= @graph.visualization_name %>
</p>


<%= link_to 'Edit', edit_graph_path(@graph) %> |
<%= link_to 'Back', graphs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Graphene2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="/assets/d3/d3.v3.js"></script>
  <script src="/assets/d3/d3.v3.min.js"></script>
  <script type="text/javascript" src="/assets/d3/d3.geom.js"></script>
      <script type="text/javascript" src="/assets/d3/d3.csv.js"></script>
    <script type="text/javascript" src="/assets/d3/d3.geo.js"></script>

</head>
<body>

<%= yield %>

</body>
</html>